import com.rrpictureproductions.chess.crossproduct
import com.rrpictureproductions.chess.toPosition

/**
 * Created by robin on 16.02.2017.
 */

val A1 = "A1".toPosition()
val A2 = "A2".toPosition()
val A3 = "A3".toPosition()
val A4 = "A4".toPosition()
val A5 = "A5".toPosition()
val A6 = "A6".toPosition()
val A7 = "A7".toPosition()
val A8 = "A8".toPosition()
val B1 = "B1".toPosition()
val B2 = "B2".toPosition()
val B3 = "B3".toPosition()
val B4 = "B4".toPosition()
val B5 = "B5".toPosition()
val B6 = "B6".toPosition()
val B7 = "B7".toPosition()
val B8 = "B8".toPosition()
val C1 = "C1".toPosition()
val C2 = "C2".toPosition()
val C3 = "C3".toPosition()
val C4 = "C4".toPosition()
val C5 = "C5".toPosition()
val C6 = "C6".toPosition()
val C7 = "C7".toPosition()
val C8 = "C8".toPosition()
val D1 = "D1".toPosition()
val D2 = "D2".toPosition()
val D3 = "D3".toPosition()
val D4 = "D4".toPosition()
val D5 = "D5".toPosition()
val D6 = "D6".toPosition()
val D7 = "D7".toPosition()
val D8 = "D8".toPosition()
val E1 = "E1".toPosition()
val E2 = "E2".toPosition()
val E3 = "E3".toPosition()
val E4 = "E4".toPosition()
val E5 = "E5".toPosition()
val E6 = "E6".toPosition()
val E7 = "E7".toPosition()
val E8 = "E8".toPosition()
val F1 = "F1".toPosition()
val F2 = "F2".toPosition()
val F3 = "F3".toPosition()
val F4 = "F4".toPosition()
val F5 = "F5".toPosition()
val F6 = "F6".toPosition()
val F7 = "F7".toPosition()
val F8 = "F8".toPosition()
val G1 = "G1".toPosition()
val G2 = "G2".toPosition()
val G3 = "G3".toPosition()
val G4 = "G4".toPosition()
val G5 = "G5".toPosition()
val G6 = "G6".toPosition()
val G7 = "G7".toPosition()
val G8 = "G8".toPosition()
val H1 = "H1".toPosition()
val H2 = "H2".toPosition()
val H3 = "H3".toPosition()
val H4 = "H4".toPosition()
val H5 = "H5".toPosition()
val H6 = "H6".toPosition()
val H7 = "H7".toPosition()
val H8 = "H8".toPosition()

fun main(args: Array<String>) {
    ('A'..'H').asSequence().crossproduct((1..8).asSequence()).forEach { println("${it.first}${it.second}") }
}